### ISSUE TITLE
怎么开启创建mindmap？没有使用手册，使用说明

### ISSUE THREAD

**Issue by ajiasha** [shaunhurryup/lovely-mindmap#9]
怎么开启创建mindmap？没有使用手册，使用说明，我不知道如何打开mindmap去画思维导图，没有任何方式，cmd+P不行，右上角···也没有

**Comment by shaunhurryup** [comment]
obsidian 并没有 mindmap 这一概念，所谓的 mindmap（思维导图）在 canvas 模式下才能使用。

你需要先创建画板，我们封装了些快捷键来模拟出 mindmap 的操作。

但请记住，canvas 远比 mindmap 强大的多

<img width="1024" alt="image" src="https://github.com/shaunhurryup/lovely-mindmap/assets/45918719/cee7d3cf-0315-4633-a6e0-21eaea680bb4">

有些东西我们默认使用方知道的
